version: '3'

services:
  nodejs:
    build: 
      context: ./node-app
    image: gabryellows/app
    container_name: nodejs
    entrypoint: wait-for db:3306 -t 40 -- npm start
    networks:
      - node-network
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    volumes:
      - database:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  nginx:
    build: 
      context: ./nginx
    image: gabryellows/nginx
    container_name: nginx
    networks:
      - node-network
    entrypoint: wait-for db:3306 -t 40 -- nginx -g "daemon off;" 
    ports:
      - 8080:80
    depends_on:
      - nodejs

volumes:
  database:

networks:
  node-network:
    driver: bridge